# Generated by Django 4.2.6 on 2025-04-03 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "attended",
                    models.BooleanField(default=False, verbose_name="attended"),
                ),
                (
                    "cancelled",
                    models.BooleanField(default=False, verbose_name="cancelled"),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="cancellation reason"
                    ),
                ),
            ],
            options={
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("health_notes", models.TextField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FitnessClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="class name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "instructor",
                    models.CharField(max_length=100, verbose_name="instructor"),
                ),
                (
                    "class_type",
                    models.CharField(
                        choices=[
                            ("yoga", "Yoga"),
                            ("pilates", "Pilates"),
                            ("hiit", "HIIT"),
                            ("cycling", "Cycling"),
                            ("strength", "Strength Training"),
                            ("dance", "Dance"),
                        ],
                        default="yoga",
                        max_length=20,
                        verbose_name="class type",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="start time")),
                ("end_time", models.DateTimeField(verbose_name="end time")),
                ("capacity", models.PositiveIntegerField(verbose_name="capacity")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=6,
                        verbose_name="price",
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="location")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="class_images/",
                        verbose_name="class image",
                    ),
                ),
            ],
            options={
                "verbose_name": "fitness class",
                "verbose_name_plural": "fitness classes",
                "ordering": ["start_time"],
                "indexes": [
                    models.Index(
                        fields=["start_time"], name="booking_fit_start_t_05378e_idx"
                    ),
                    models.Index(
                        fields=["class_type"], name="booking_fit_class_t_634e51_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="fitnessclass",
            constraint=models.CheckConstraint(
                check=models.Q(("end_time__gt", models.F("start_time"))),
                name="end_time_after_start_time",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="fitness_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="booking.fitnessclass",
                verbose_name="fitness class",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "fitness_class"], name="booking_boo_user_id_88e504_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("user", "fitness_class")},
        ),
    ]
